[package]
name = "esp-pbuf"
version = "0.0.0"
edition = "2021"

[build-dependencies]
embuild = "0.31"

[dependencies]
esp-idf-sys = { version = "0.33", default-features = false, features = ["native"] }

[package.metadata.esp-idf-sys]
esp_idf_version = "v5.1"
