[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["core", "panic_abort"]
